#Python CircleCI 2.0 confirguration file
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/python:3.7
      working_directory: /home/circleci/project
      steps:
                  # Obtain repo from the GitHub
        - checkout
                  # Create a virtual environment and install dependencies
        - run:
            name: install dependencies
            command: |
              pwd      
              python3 -m venv venv
              . venv/bin/activate
              /home/circleci/project/venv/bin/python3 -m pip install --upgrade pip
              pip install -r myreq.txt
                  # Run coding convention software plus tester
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
                                # pytest -v --cov=calculator
              pytest --junitxml=test-results/junit.xml
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results